name: breez_preferences
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  shared_preferences: ^2.2.3
  shared_preference_app_group: ^1.1.1 # iOS Notification Service extension requirement to access shared preferences
  logging: ^1.2.0